# yaml 配置实例
version: '3'
services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    networks:
#      - app
#    depends_on:
#      - redis
#      - mysql
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ${DOCKER_DIR}/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app
networks:
  app:
    driver: bridge